### ISSUE TITLE
Сохранение и применение параметров «Место работы» в настройках фильтра.

### ISSUE THREAD

**Issue by LuchikSakuras** [FantasmasDev/sugar-hunter#119]
- [x] Выбранные страна отображается на экране настроек параметров фильтрации поисковых запросов.
- [x] Выбранный регион отображаются на экране настроек параметров фильтрации поисковых запросов. Если выбрана только страна, то отображается только страна. Если выбран регион, то отображается страна и регион.

**Comment by muskilon** [comment]
в рамках #131
