### ISSUE TITLE
Логика экрана «Выбор региона».

### ISSUE THREAD

**Issue by LuchikSakuras** [FantasmasDev/sugar-hunter#122]
**Приступать к этой таске только после того, как будет вмержена навигация**
**ВАЖНО**: работать только в своем фрагменте и вью модели

- [x] Если приложению не удалось получить список регионов, то на экране выбора региона пользователь видит соответствующий плейсхолдер. В противном случае пользователь видит список регионов.
- [x] Если поле ввода поискового запроса не пустое, то в списке присутствуют только те регионы, названия которых содержат введённый в поле текст.
- [x] Допустима реализация фильтрации списка на уровне адаптера или с использованием ViewModel.
- [x] Написать метод, который будет **только передавать** информацию по выбранному региону (о способе договоритесь с тем, кто делает логику экрана Выбор места работы)
- [x] Когда пользователь на экране выбора региона нажимает на элемент списка регионов, он возвращается на экран выбора места работы 
- [x] Если в настройках фильтрации уже есть выбранная страна, то при переходе на экран выбора региона пользователь видит список только тех регионов, которые относятся к выбранной стране. В противном случае пользователь видит список всех доступных регионов, которые не являются странами.

**Comment by muskilon** [comment]
сделано или будет сделано в #131
