### ISSUE TITLE
Рефакторинг выбора места работы и фильтров

### ISSUE THREAD

**Issue by muskilon** [FantasmasDev/sugar-hunter#141]

**Comment by FantasmasDev** [comment]
только фильтров, место работы маше с трудом далось, но баги она убрала, максимум ключи для передачи данных, надо выходить на сдачу проекта

**Comment by FantasmasDev** [comment]
загляни в 102, там галки по фильтрам есть

**Comment by FantasmasDev** [comment]
в 136, нужен фикс
