### ISSUE TITLE
16 Retrofit !Ключа нет! смотри описание внимательно

### ISSUE THREAD

**Issue by FantasmasDev** [FantasmasDev/sugar-hunter#42]
- [ ] Retrofit максимально простая реализация
- [ ] Создать Retrofit API interface с suspend-методом для выполнения поискового запроса, сетевой запрос не должен быть в основном потоке
- [ ] Для поискового запроса в пакете data.dto создать классы запроса (Request) и ответа (Response), DTO классы не должны использоваться за пределами Data слоя
- [ ] DTO и Domain-классы содержат параметры page и pages, использующиеся для пагинации.
Размер страницы 20 элементов.
- [ ] Метод запроса - > [QueryMap ](https://practicum.yandex.ru/learn/android-developer/courses/8e512d47-6da3-4ab6-8464-aff40d0c0a31/sprints/195789/topics/174a1fab-ce65-4a2f-a606-4f543d30c754/lessons/e56b5398-c90a-4488-9b3e-291ddc382888/#:~:text=%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%20QueryMap.-,QueryMap,-%D0%A0%D0%B0%D1%81%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B8%D0%BC%20%D0%BF%D1%80%D0%BE%D1%81%D1%82%D0%BE%D0%B9%20%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80)
- [ ] Реализовать логику фильтрации сетевого запроса (коды 200 400)
- [ ] все необходимые интерфейсы и Интеракторы, чтобы запустить этот метод в viewmodel
- [ ] согласуйся с верстальщиком, кто создаст MutableLiveData в VM, в ней храните запрос из сети, чтобы выводить его, на экран
(Предлагаю верстальщика)
- [ ] Проверь работу метода совместно с верстальщиком

**Comment by muskilon** [comment]
вот эти два пункта не готовы:
DTO и Domain-классы содержат параметры page и pages, использующиеся для пагинации.
Размер страницы 20 элементов.
 Метод запроса - > [QueryMap](https://practicum.yandex.ru/learn/android-developer/courses/8e512d47-6da3-4ab6-8464-aff40d0c0a31/sprints/195789/topics/174a1fab-ce65-4a2f-a606-4f543d30c754/lessons/e56b5398-c90a-4488-9b3e-291ddc382888/#:~:text=%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%20QueryMap.-,QueryMap,-%D0%A0%D0%B0%D1%81%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B8%D0%BC%20%D0%BF%D1%80%D0%BE%D1%81%D1%82%D0%BE%D0%B9%20%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80)
