### ISSUE TITLE
24 Room

### ISSUE THREAD

**Issue by FantasmasDev** [FantasmasDev/sugar-hunter#50]
- [x] Хранение информации об избранных вакансиях реализовано в базе данных, сконфигурированной и управляемой при помощи библиотеки Room.

- [x] В Data-слое описан Entity-класс, содержащий все данные для отображения информации о вакансии.

- [x] Описан DAO-интерфейс, позволяющий сохранить вакансию в базу, удалить её, и получить список всех избранных вакансий или отдельную избранную вакансию по идентификатору.

- [x] База данных сконфигурирована с использованием созданной Entitiy и DAO-интерфейса.

- [x] Описан и реализован Repository, предоставляющий метод для добавления вакансии в список избранных, 

- [x] удаления вакансии из этого списка, получения списка избранных вакансий и получения информации об избранной вакансии по идентификатору.

- [x] Описан и реализован Interactor, обеспечивающий ViewModel связь с Domain-слоем.

- [x] Интерактор, обеспечивающий работу с избранными вакансиями, должен быть внедрён как зависимости в ViewModel экранов «Избранное» и «Вакансия».

**Comment by LuchikSakuras** [comment]
выполнила в рамках 23 таска
